---
# Title: UrBackup server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: handlers/main.yml
#
# Description:
#   Playbook for UrBackup server
#   on a Ubuntu server.
#
- name: "reload_apache2"
  systemd:
    state: reloaded
    name: apache2

- name: "restart_apache2"
  systemd:
    state: restarted
    name: apache2
